global:
  resolve_timeout: 5m
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        text: |
          [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} 
          {{ .CommonAnnotations.summary }}
        send_resolved: true
        api_url_file: https://hooks.slack.com/services/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
route:
  receiver: 'slack-notifications'
  group_wait: 0s
  group_interval: 10s
  repeat_interval: 15m

