global:
  resolve_timeout: 5m
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        text: |
          [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} 
          {{ .CommonAnnotations.summary }}
        send_resolved: true
        api_url: ${SLACK_WEBHOOK_URL}
route:
  receiver: 'slack-notifications'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
