global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - /etc/prometheus/rules/*.yaml
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']
scrape_configs:
  - job_name: 'monitoring-app'
    static_configs:
      - targets: ['go-server-service.default.svc.cluster.local:8080']